### ISSUE TITLE
Ferris is having trouble with a missing attribute on the "endpoints" module....

### ISSUE THREAD

**Issue by dgaedcke** [jonparrott/ferris3#29]
```
Traceback (most recent call last):
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
    handler, path, err = LoadObject(self._handler)
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
    __import__(cumulative_path)
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/main.py", line 9, in <module>
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/main.py", line 9, in <module>
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/main.py", line 9, in <module>
    import endpoint_config     # establishes the endpoint 'tstone' in registry as the default
    import endpoint_config     # establishes the endpoint 'tstone' in registry as the default
    import endpoint_config     # establishes the endpoint 'tstone' in registry as the default
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/endpoint_config.py", line 4, in <module>
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/endpoint_config.py", line 4, in <module>
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/endpoint_config.py", line 4, in <module>
    endpoints.add('service_backend/endpoint_config.yaml', default=True)
    endpoints.add('service_backend/endpoint_config.yaml', default=True)
    endpoints.add('service_backend/endpoint_config.yaml', default=True)
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/venv/lib/python2.7/site-packages/ferris3/endpoints.py", line 37, in add
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/venv/lib/python2.7/site-packages/ferris3/endpoints.py", line 37, in add
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/venv/lib/python2.7/site-packages/ferris3/endpoints.py", line 37, in add
    config = load_config_file(config_or_file)
    config = load_config_file(config_or_file)
    config = load_config_file(config_or_file)
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/venv/lib/python2.7/site-packages/ferris3/endpoints.py", line 91, in load_config_file
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/venv/lib/python2.7/site-packages/ferris3/endpoints.py", line 91, in load_config_file
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/venv/lib/python2.7/site-packages/ferris3/endpoints.py", line 91, in load_config_file
    recursive_replace(config, 'API_EXPLORER_CLIENT_ID', endpoints.API_EXPLORER_CLIENT_ID)
AttributeError: 'module' object has no attribute 'API_EXPLORER_CLIENT_ID'
    recursive_replace(config, 'API_EXPLORER_CLIENT_ID', endpoints.API_EXPLORER_CLIENT_ID)
    recursive_replace(config, 'API_EXPLORER_CLIENT_ID', endpoints.API_EXPLORER_CLIENT_ID)
AttributeError: 'module' object has no attribute 'API_EXPLORER_CLIENT_ID'
```

**Comment by jonparrott** [comment]
Thanks for reporting this. I'm going to try to reproduce. If I can't, I'll have to ask for some more info.

**Comment by jonparrott** [comment]
I couldn't reproduce this with the skeleton. :(

Can you modify `ferris3/endpoints.py` to print the following details?

```
import sys
print(sys.modules['endpoints'].__file__)
```

**Comment by dgaedcke** [comment]
yes....I got:

endpoints file is:
/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/lib/endpoints-1.0/endpoints/__init__.pyc

**Comment by jonparrott** [comment]
That's.. strange. My assumption was that it was importing ferris' endpoints module instead of the app engine endpoints, but it seems that my hypothesis is incorrect.

You added that in `ferris3/endpoints.py`, right?

**Comment by dgaedcke** [comment]
correct...here is the file header from .../site-packages/ferris3/endpoints.py

from __future__ import absolute_import
from protorpc import message_types
from protorpc import messages
import endpoints
from .anodi import annotated
import inspect
import re
import yaml
import os

_endpoints = {}
_default_endpoint_name = None

base_directory = os.getcwd()

import sys
print('endpoints file is:')
print(sys.modules['endpoints'].__file__)

**Comment by jonparrott** [comment]
I'm very curious as to why I can't reproduce this myself. Does this happen if you start a fresh project with the skeleton?

**Comment by dgaedcke** [comment]
I'm back to hitting this error again.....so I'll start a fresh project now and report my findings....

**Comment by dgaedcke** [comment]
not getting any problems with the skeleton....but my project has 4 separate modules and ferris3 seems to be loading correctly in the first one......when I try to import it in the first module it works fine...it's failing in the 2nd module ( running on dev-server)

Oh, wait, this is a different error than the one listed above....its:
  File "~/dev/TouchstoneMicroservices/lib/ferris3/endpoints.py", line 96, in load_config_file
    'required': endpoints.AUTH_LEVEL.REQUIRED,
AttributeError: 'module' object has no attribute 'AUTH_LEVEL'

when I look in the config yaml file, auth_level is there but it's lowercase.....
let me know if you want me to create a new ticket....

I fixed the orig error above by adding the following to my appengine_config.py:
import endpoints
endpoints.API_EXPLORER_CLIENT_ID = '2xxxxxxxx2.apps.googleusercontent.com'

**Comment by dgaedcke** [comment]
ok...silly me
I found the problem:  I had older copies of both endpoints and protorpc in my /lib directory instead of letting google provision them via:   service.yaml->libraries
I'm kind of surprised that any of my services were running properly.....

**Comment by jonparrott** [comment]
Glad you got it sorted!
