### ISSUE TITLE
work abandoned?

### ISSUE THREAD

**Issue by afzalSH** [jonparrott/ferris3#32]
Is this an abandoned work? For one, the python package is not up to date with the library. And is there a plan to upgrade to endpoints 2.0?

**Comment by jonparrott** [comment]
Since endpoints 2.0 works with OpenAPI / Swagger and allows you to use any REST framework you want,    this library isn't as useful.

I've offered several times to allow Cloud Sherpas to take over, but they do not seem interested in continuing maintenance. If someone does indeed want to take over, I'll be happy to discuss how that can happen.

**Comment by SpainTrain** [comment]
Thanks for the update :+1:.

Are there other options than https://github.com/zalando/connexion?  It seems like for existing App Engine apps, the easiest migration path is using the new Cloud Endpoints Frameworks.  Does this sound right?

**Comment by dgaedcke** [comment]
I just upgraded to endpoints 2.0 and I'm hitting the below error.
based on reading the above, do I need to rip Ferris out of my project??

ERROR    2018-07-26 00:03:00,724 wsgi.py:263] 
Traceback (most recent call last):
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/dgaedcke/gcloud_tools/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/main.py", line 9, in <module>
    import endpoint_config     # establishes the endpoint 'tstone' in registry as the default
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/service_backend/endpoint_config.py", line 1, in <module>
    from ferris3 import endpoints
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/lib/ferris3/__init__.py", line 3, in <module>
    from . import ndb, messages, template, settings, hvild
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/lib/ferris3/messages.py", line 1, in <module>
    import protopigeon
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/lib/protopigeon/__init__.py", line 1, in <module>
    from protorpc.messages import *
  File "/Users/dgaedcke/dev/TouchstoneMicroservices/lib/protorpc/messages.py", line 1146, in <module>
    class Field(six.with_metaclass(_FieldMeta, object)):
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
INFO     2018-07-26 00:03:00,745 module.py:878] default: "POST /_ah/api/tstone/v1/user/createOrLoadUser?prettyPrint=false HTTP/1.1" 500 -

**Comment by dgaedcke** [comment]
and if so, any tips on how best (easiest) to do that would be most welcome.  I'm not too familiar with all the Google tools.

**Comment by theacodes** [comment]
I mean, yeah, this libraries' usefulness is becoming vanishingly small. I'd move to just plain endpoints 2 if I were you.

**Comment by dgaedcke** [comment]
thanks for the response!!  Would you happen to know of a good example to show me what to replace the Ferris wrapper commands with?  In other words, how will my Python syntax need to change to convert from F3 to Endpoints2.

**Comment by theacodes** [comment]
Honestly I don't even know anymore. I'd say start from scratch. If you have
an established project it's probably better for fork ferris3 and fix
whatever issues you're running into.
